### PR TITLE
Post message as SlackBot with --as-slackbot & --team

### LINKED ISSUE #18: Support Slackbot Remote Control
https://api.slack.com/slackbot

```
curl --data "Hello from Slackbot" $'https://my.slack.com/services/hooks/slackbot?token=oLqLmTpxS5rDKghRQe5qbd9K&channel=%23general'
```

with

```
echo "Hello from Slackbot" | slacker -c general --as-slackbot
```

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #18

### CODE REVIEW

**Comment by wkentaro** [comment]
*Example from https://api.slack.com/slackbot*
```
curl --data "Hello from Slackbot" $'https://my.slack.com/services/hooks/slackbot?token=oLqLmTpxS5rDKghRQe5qbd9K&channel=%23general'
```

as

```
echo ""Hello from Slackbot" | slacker --token oLqLmTpxS5rDKghRQe5qbd9K --channel general --team my
```

or

```
export SLACK_TEAM=my
export SLACKBOT_TOKEN=oLqLmTpxS5rDKghRQe5qbd9K
echo ""Hello from Slackbot" | slacker --channel general
```

**Comment by juanpabloaj** [comment]
thanks @wkentaro , I will check the changes and make the merge

**Comment by juanpabloaj** [comment]
@wkentaro after make the merge and upload to pypi, when I try to install I get this error

```bash
pip install slacker-cli
Downloading/unpacking slacker-cli
  Downloading slacker-cli-0.2.4.tar.gz
  Running setup.py (path:/Users/pablo/envs/slacker-cli/build/slacker-cli/setup.py) egg_info for package slacker-cli
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/pablo/envs/slacker-cli/build/slacker-cli/setup.py", line 14, in <module>
        install_requires = read('requirements.txt').splitlines()
      File "/Users/pablo/envs/slacker-cli/build/slacker-cli/setup.py", line 10, in read
        with open(os.path.join(*paths), 'r') as filename:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/pablo/envs/slacker-cli/build/slacker-cli/setup.py", line 14, in <module>

    install_requires = read('requirements.txt').splitlines()

  File "/Users/pablo/envs/slacker-cli/build/slacker-cli/setup.py", line 10, in read

    with open(os.path.join(*paths), 'r') as filename:

IOError: [Errno 2] No such file or directory: 'requirements.txt'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/pablo/envs/slacker-cli/build/slacker-cli
Storing debug log for failure in /Users/pablo/.pip/pip.log
```

**Comment by juanpabloaj** [comment]
maybe this problem is because by default the `requirements.txt` is not attached to the package.

I think this problem is related to the commit 9a5aa06951c5105d3d48522b019185cbf85faa59

**Comment by wkentaro** [comment]
See https://github.com/juanpabloaj/slacker-cli/pull/20

**Pull request merged**
