### PR TITLE
Can send DM to user

### LINKED ISSUE #15: --username option does not work

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #15
- [x] ~~wait for os/slacker#46 to be merged~~ (See https://github.com/juanpabloaj/slacker-cli/pull/17#issuecomment-147653902)

### CODE REVIEW

**Comment by wkentaro** [comment]
Depends on https://github.com/os/slacker/pull/46

**Comment by juanpabloaj** [comment]
@wkentaro thanks for the pull request. 

this pull request broke the tests because depend the pull request in slacker library?

**Comment by wkentaro** [comment]
yeah, I think so. it fails because of ImportError.

**Comment by juanpabloaj** [comment]
ok, I wait for the merge of pull request in os/slacker library and make this merge

thanks again for the pull request :)

**Comment by wkentaro** [comment]
added this line for direct message to `slackbot` channel.
https://github.com/juanpabloaj/slacker-cli/pull/17/files#diff-dd7b63603ef69c061b196e16eab8f328R103

**Comment by wkentaro** [comment]
https://github.com/os/slacker/pull/46 is not merged a long time.
So I add the dependent function to slacker-cli, and I will remove after the PR is merged to os/slacker.

**Comment by wkentaro** [comment]
@juanpabloaj 
Please review and merge if it's fine.

**Comment by juanpabloaj** [comment]
Ok @kentaro when I get home I review this PR , thanks :)



—
JuanpabloAJjuanpabloaj.com

**Pull request merged**
